<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <OutputPath>..\bin\ForktierMail.Server\</OutputPath>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <ServerGarbageCollection>true</ServerGarbageCollection>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\ForktierMail.Shared\ForktierMail.Shared.csproj"/>
        <ProjectReference Include="..\ForktierMail.Database\ForktierMail.Database.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.MessagePack"/>
    </ItemGroup>
</Project>