<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="NUnit"/>
        <PackageReference Include="NUnit.Analyzers"/>
        <PackageReference Include="NUnit3TestAdapter"/>
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing"/>
        <PackageReference Include="Microsoft.AspNetCore.TestHost"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="NUnit.Framework"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ForktierMail.Database\ForktierMail.Database.csproj"/>
        <ProjectReference Include="..\ForktierMail.Server\ForktierMail.Server.csproj"/>
        <ProjectReference Include="..\ForktierMail.Client\ForktierMail.Client.csproj"/>
        <ProjectReference Include="..\ForktierMail.Shared\ForktierMail.Shared.csproj"/>
    </ItemGroup>
</Project>
